# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=15, null=True)),
                ('created_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(unique=True, verbose_name='Roll No')),
                ('full_name', models.CharField(max_length=120, verbose_name='Full Name')),
                ('web_mail', models.CharField(max_length=60, verbose_name='Web-mail')),
                ('gender', models.CharField(choices=[(b'Male', b'Male'), (b'Female', b'Female')], max_length=6)),
                ('department', models.CharField(choices=[(b'BioSciences and Bioengineering', b'BioSciences and Bioengineering'), (b'Chemistry', b'Chemistry'), (b'Chemical Engineering', b'Chemical Engineering'), (b'Civil Engineering', b'Civil Engineering'), (b'Computer Science and Engineering', b'Computer Science and Engineering'), (b'Design', b'Design'), (b'Electronics and Electrical Engineering', b'Electronics and Electrical Engineering'), (b'Electronics and Communication Engineering', b'Electronics and Communication Engineering'), (b'Humanities & Social Sciences', b'Humanities & Social Sciences'), (b'Mathematics', b'Mathematics'), (b'Mechanical Engineering', b'Mechanical Engineering'), (b'Physics', b'Physics'), (b'Center for Energy', b'Center for Energy')], max_length=120)),
                ('programme', models.CharField(choices=[(b'B.Tech.', b'B.Tech.'), (b'B.Des.', b'B.Des.'), (b'M.Tech.', b'M.Tech.'), (b'M.Des.', b'M.Des.'), (b'Ph.D.', b'Ph.D.'), (b'M.Sc.', b'M.Sc.'), (b'M.A.', b'M.A.'), (b'MSR', b'MSR')], max_length=20)),
                ('token_booked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['roll_no'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Slot'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set([('student', 'slot')]),
        ),
    ]
