# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_slot_stud_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='max_limit',
            field=models.IntegerField(default=100),
        ),
    ]
